### ISSUE TITLE
Publish game to D package registry

### ISSUE THREAD

**Issue by denizzzka** [nilsding/crash-game#1]
Otherwise `dub fetch crash-game` isn't works:

```
$ dub fetch crash-game
Getting a release version failed: No package crash-game was found matching the dependency >=0.0.0
Retry with ~master...
No package crash-game was found matching the dependency ~master
```

**Comment by denizzzka** [comment]
Oops! Mine mistake: code.dlang.org isn't know this game package

**Comment by nilsding** [comment]
Hm, so you want me to publish this on the D package registry?  I could do that, just give me a while.

**Comment by nilsding** [comment]
You can now install this game using `dub fetch crash-game`, and then run it using `dub run crash-game` 🎉
